[[constraint]]
  name = "github.com/gambol99/go-marathon"
  version = "0.7.1"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
